/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimpleReactionRouteImport } from './routes/simple-reaction'
import { Route as PhysicalMatchingRouteImport } from './routes/physical-matching'
import { Route as NameMatchingRouteImport } from './routes/name-matching'
import { Route as IndexRouteImport } from './routes/index'

const SimpleReactionRoute = SimpleReactionRouteImport.update({
  id: '/simple-reaction',
  path: '/simple-reaction',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysicalMatchingRoute = PhysicalMatchingRouteImport.update({
  id: '/physical-matching',
  path: '/physical-matching',
  getParentRoute: () => rootRouteImport,
} as any)
const NameMatchingRoute = NameMatchingRouteImport.update({
  id: '/name-matching',
  path: '/name-matching',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/name-matching': typeof NameMatchingRoute
  '/physical-matching': typeof PhysicalMatchingRoute
  '/simple-reaction': typeof SimpleReactionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/name-matching': typeof NameMatchingRoute
  '/physical-matching': typeof PhysicalMatchingRoute
  '/simple-reaction': typeof SimpleReactionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/name-matching': typeof NameMatchingRoute
  '/physical-matching': typeof PhysicalMatchingRoute
  '/simple-reaction': typeof SimpleReactionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/name-matching' | '/physical-matching' | '/simple-reaction'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/name-matching' | '/physical-matching' | '/simple-reaction'
  id:
    | '__root__'
    | '/'
    | '/name-matching'
    | '/physical-matching'
    | '/simple-reaction'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NameMatchingRoute: typeof NameMatchingRoute
  PhysicalMatchingRoute: typeof PhysicalMatchingRoute
  SimpleReactionRoute: typeof SimpleReactionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simple-reaction': {
      id: '/simple-reaction'
      path: '/simple-reaction'
      fullPath: '/simple-reaction'
      preLoaderRoute: typeof SimpleReactionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physical-matching': {
      id: '/physical-matching'
      path: '/physical-matching'
      fullPath: '/physical-matching'
      preLoaderRoute: typeof PhysicalMatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/name-matching': {
      id: '/name-matching'
      path: '/name-matching'
      fullPath: '/name-matching'
      preLoaderRoute: typeof NameMatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NameMatchingRoute: NameMatchingRoute,
  PhysicalMatchingRoute: PhysicalMatchingRoute,
  SimpleReactionRoute: SimpleReactionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
