/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisualSearchRouteImport } from './routes/visual-search'
import { Route as SimpleReactionRouteImport } from './routes/simple-reaction'
import { Route as PhysicalMatchingRouteImport } from './routes/physical-matching'
import { Route as NameMatchingRouteImport } from './routes/name-matching'
import { Route as ClassMatchingRouteImport } from './routes/class-matching'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryGameRouteImport } from './routes/history.$game'

const VisualSearchRoute = VisualSearchRouteImport.update({
  id: '/visual-search',
  path: '/visual-search',
  getParentRoute: () => rootRouteImport,
} as any)
const SimpleReactionRoute = SimpleReactionRouteImport.update({
  id: '/simple-reaction',
  path: '/simple-reaction',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysicalMatchingRoute = PhysicalMatchingRouteImport.update({
  id: '/physical-matching',
  path: '/physical-matching',
  getParentRoute: () => rootRouteImport,
} as any)
const NameMatchingRoute = NameMatchingRouteImport.update({
  id: '/name-matching',
  path: '/name-matching',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassMatchingRoute = ClassMatchingRouteImport.update({
  id: '/class-matching',
  path: '/class-matching',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryGameRoute = HistoryGameRouteImport.update({
  id: '/history/$game',
  path: '/history/$game',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/class-matching': typeof ClassMatchingRoute
  '/name-matching': typeof NameMatchingRoute
  '/physical-matching': typeof PhysicalMatchingRoute
  '/simple-reaction': typeof SimpleReactionRoute
  '/visual-search': typeof VisualSearchRoute
  '/history/$game': typeof HistoryGameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/class-matching': typeof ClassMatchingRoute
  '/name-matching': typeof NameMatchingRoute
  '/physical-matching': typeof PhysicalMatchingRoute
  '/simple-reaction': typeof SimpleReactionRoute
  '/visual-search': typeof VisualSearchRoute
  '/history/$game': typeof HistoryGameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/class-matching': typeof ClassMatchingRoute
  '/name-matching': typeof NameMatchingRoute
  '/physical-matching': typeof PhysicalMatchingRoute
  '/simple-reaction': typeof SimpleReactionRoute
  '/visual-search': typeof VisualSearchRoute
  '/history/$game': typeof HistoryGameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/class-matching'
    | '/name-matching'
    | '/physical-matching'
    | '/simple-reaction'
    | '/visual-search'
    | '/history/$game'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/class-matching'
    | '/name-matching'
    | '/physical-matching'
    | '/simple-reaction'
    | '/visual-search'
    | '/history/$game'
  id:
    | '__root__'
    | '/'
    | '/class-matching'
    | '/name-matching'
    | '/physical-matching'
    | '/simple-reaction'
    | '/visual-search'
    | '/history/$game'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClassMatchingRoute: typeof ClassMatchingRoute
  NameMatchingRoute: typeof NameMatchingRoute
  PhysicalMatchingRoute: typeof PhysicalMatchingRoute
  SimpleReactionRoute: typeof SimpleReactionRoute
  VisualSearchRoute: typeof VisualSearchRoute
  HistoryGameRoute: typeof HistoryGameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visual-search': {
      id: '/visual-search'
      path: '/visual-search'
      fullPath: '/visual-search'
      preLoaderRoute: typeof VisualSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simple-reaction': {
      id: '/simple-reaction'
      path: '/simple-reaction'
      fullPath: '/simple-reaction'
      preLoaderRoute: typeof SimpleReactionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physical-matching': {
      id: '/physical-matching'
      path: '/physical-matching'
      fullPath: '/physical-matching'
      preLoaderRoute: typeof PhysicalMatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/name-matching': {
      id: '/name-matching'
      path: '/name-matching'
      fullPath: '/name-matching'
      preLoaderRoute: typeof NameMatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class-matching': {
      id: '/class-matching'
      path: '/class-matching'
      fullPath: '/class-matching'
      preLoaderRoute: typeof ClassMatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$game': {
      id: '/history/$game'
      path: '/history/$game'
      fullPath: '/history/$game'
      preLoaderRoute: typeof HistoryGameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClassMatchingRoute: ClassMatchingRoute,
  NameMatchingRoute: NameMatchingRoute,
  PhysicalMatchingRoute: PhysicalMatchingRoute,
  SimpleReactionRoute: SimpleReactionRoute,
  VisualSearchRoute: VisualSearchRoute,
  HistoryGameRoute: HistoryGameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
